### ISSUE TITLE
what does "no PORT environment variable found" mean?

### ISSUE THREAD

**Issue by luckypoem** [snoyberg/snoyman.com#1]
hi.

root@AR:/usr/local/snoyman.com# ls
dev.sh	LICENSE  README.md  snoymancom.cabal  templates
kube	main.hs  Setup.hs   stack.yaml
root@AR:/usr/local/snoyman.com# stack build

it shows:
...
Linking .stack-work/dist/i386-linux/Cabal-1.22.5.0/build/snoymancom/snoymancom ...
Warning: File listed in snoymancom.cabal file does not exist: README
snoymancom-0.1.0.0: copy/register
Installing executable(s) in
/usr/local/snoyman.com/.stack-work/install/i386-linux/lts-6.11/7.10.3/bin
Completed 166 action(s).
root@AR:/usr/local/snoyman.com#

root@AR:/usr/local/snoyman.com# git clone https://github.com/snoyberg/snoyman.com-content
root@AR:/usr/local/snoyman.com# ls
dev.sh	LICENSE  README.md  snoymancom.cabal	 stack.yaml
kube	main.hs  Setup.hs   snoyman.com-content  templates
root@AR:/usr/local/snoyman.com# ls snoyman.com-content
blog-style.lucius  home.yaml  posts	  robots.txt  style.lucius
favicon.ico	   img	      posts.yaml  static      torah
root@AR:/usr/local/snoyman.com# mv snoyman.com-content/* .
root@AR:/usr/local/snoyman.com# ls snoyman.com-content/
root@AR:/usr/local/snoyman.com# rm -rf snoyman.com-content
root@AR:/usr/local/snoyman.com# .stack-work/dist/i386-linux/Cabal-1.22.5.0/build/snoymancom/snoymancom build
cloning to '/tmp/git-repo27475'...
remote: Counting objects: 216, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 216 (delta 24), reused 0 (delta 0), pack-reused 174
Receiving objects: 100% (216/216), 1.06 MiB | 312 KiB/s, done.
Resolving deltas: 100% (103/103), done.
snoymancom: warpEnv: no PORT environment variable found
root@AR:/usr/local/snoyman.com#

thank u

**Comment by snoyberg** [comment]
This repo is not really intended for others to be using, so there are plenty of rough edges. That said, setting your PORT env var (e.g. `export PORT=3000`) will fix this. It's also intended to work with `yesod devel`.
