### ISSUE TITLE
Can't add RSS feed

### ISSUE THREAD

**Issue by maurges** [snoyberg/snoyman.com#2]
Is it not there or is my reader unable to find the correct url? What's the feed url if it exists?

**Comment by snoyberg** [comment]
It's https://www.snoyman.com/feed. I'll make sure to add appropriate metadata for that.

**Comment by maurges** [comment]
Thanks! I tried that link and now I'm getting strange errors from different readers:
```
Error when trying to subscribe feed: <unknown>:7:2: mismatched tag
```
from one, and from the other:
```
An error has occurred. The feed 'http://www.snoyman.com/feed' cannot be added (error: 'The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.')
```
Also the second reader was only able to add HTTP version and not HTTPS. This may be because of country-wide firewall, but I'm not sure.

**Comment by snoyberg** [comment]
Looks like a bug in the reader to me, or a complaint about nginx's redirect page. The feed is valid: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.snoyman.com%2Ffeed

**Comment by maurges** [comment]
Ok, thanks again!
